### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by reactexcel** [excellencetechnologies/BandWidthtracker#9]
{ Error: command failed
    at doError (/usr/local/bin/BandWidthtracker/node_modules/vnstat-dumpdb/vnstat-dumpdb.js:31:15)
    at /usr/local/bin/BandWidthtracker/node_modules/vnstat-dumpdb/vnstat-dumpdb.js:95:7
    at ChildProcess.exithandler (child_process.js:217:5)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
    at Socket.<anonymous> (internal/child_process.js:342:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at Pipe._handle.close [as _onclose] (net.js:513:12)
  error: 
   { Error: Command failed: vnstat --json
   
       at ChildProcess.exithandler (child_process.js:210:12)
       at emitTwo (events.js:106:13)
       at ChildProcess.emit (events.js:194:7)
       at maybeClose (internal/child_process.js:899:16)
       at Socket.<anonymous> (internal/child_process.js:342:11)
       at emitOne (events.js:96:13)
       at Socket.emit (events.js:191:7)
       at Pipe._handle.close [as _onclose] (net.js:513:12)
     killed: false,
     code: 1,
     signal: null,
     cmd: 'vnstat --json',
     stderr: '' },
  details: 'Error: Unable to open database directory "/var/lib/vnstat": No such file or directory\nThe vnStat daemon should have created this directory when started.\nCheck that it is is configured and running. See also "man vnstatd".\n' }

**Comment by excellencetechnologies** [comment]
this errror comes because a vnstat database is not created . for creating the vnstat database
A new database can be created with the following command:
  vnstat --create -i eth0

Replace 'eth0' with the interface that should be monitored.
